### ISSUE TITLE
Receive Callback after sharing or canceling

### ISSUE THREAD

**Issue by Dryra** [yasirkula/UnityNativeShare#43] opened 2019-07-03 08:34 UTC
Hello, 
Good job on the plugin!

This is more of a question than an issue: 
is there any way to get a callback once the content has been shared, or canceled when the native share window appears? Or if this is gonna be implemented in the future ? 
Cheers.

**Comment by yasirkula** [comment] 2019-07-03 14:13
Duplicate of https://github.com/yasirkula/UnityNativeShare/issues/5

Unfortunately this is not possible.

**Closed by yasirkula** 2019-07-03 14:13 UTC
